(()=>{const body=document.body,loader=document.getElementById('site-loader'),progress=document.querySelector('.scroll-progress'),header=document.querySelector('.site-header'),menu=document.querySelector('.menu');
/* Dark-only DEEPDELL experience */
body.classList.remove('light');localStorage.removeItem('deepdell-theme');document.querySelectorAll('.theme-toggle').forEach(el=>el.remove());const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content','#011434');
/* Brand lockup */
document.querySelectorAll('.brand img,.footer-brand img').forEach(img=>{img.src='assets/deepdell-lockup.svg';img.alt='DEEPDELL';});
/* Technical preloader */
const finishLoader=()=>{if(!loader)return;loader.classList.add('loader-done');setTimeout(()=>loader.remove(),500)};if(document.readyState==='complete')setTimeout(finishLoader,180);else window.addEventListener('load',()=>setTimeout(finishLoader,220),{once:true});
/* Mobile navigation */
menu?.addEventListener('click',()=>{const open=header.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(open));});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>header?.classList.remove('menu-open')));
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches,coarse=window.matchMedia('(pointer: coarse)').matches;
/* Scroll progress + cinematic 3D depth */
const scene=[...document.querySelectorAll('.hero-art,.shopify-visual,.dashboard,.architecture,.contact-panel,.page-hero>div')];let ticking=false;const updateScroll=()=>{const y=window.scrollY,max=document.documentElement.scrollHeight-window.innerHeight;if(progress)progress.style.width=`${max>0?Math.min(100,y/max*100):0}%`;header?.classList.toggle('scrolled',y>20);if(!reduce){const vh=window.innerHeight;scene.forEach(el=>{const r=el.getBoundingClientRect(),center=r.top+r.height/2,delta=(center-vh/2)/vh;el.style.setProperty('--scroll-tilt',`${Math.max(-5,Math.min(5,-delta*7))}deg`);el.style.setProperty('--scroll-depth',`${Math.max(-32,Math.min(32,-delta*24))}px`)});const art=document.querySelector('.hero-art');if(art){art.style.setProperty('--scroll-y',`${Math.max(-38,Math.min(18,y*.035))}px`)}}ticking=false};window.addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(updateScroll)}},{passive:true});updateScroll();
/* Scroll reveal */
const targets=document.querySelectorAll('.service,.ai-grid article,.why-grid article,.steps article,.reveal,.arch-card,.vertical,.engagement,.digital-card,.protocol,.agent-step,.ops-copy,.live-console,.page-card');if('IntersectionObserver'in window&&!reduce){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});targets.forEach(el=>{el.classList.add('reveal-item');observer.observe(el)});}else targets.forEach(el=>el.classList.add('visible'));
/* Game-like hero: cursor target, orbital parallax, reactive nodes and click pulse */
const art=document.querySelector('.hero-art');if(art&&!reduce&&!coarse){const dots=[...art.querySelectorAll('.dot')];art.addEventListener('pointerenter',()=>art.classList.add('is-hovering'));art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.setProperty('--mx',`${x*16}px`);art.style.setProperty('--my',`${y*12}px`);art.style.setProperty('--rx',`${-y*4}deg`);art.style.setProperty('--ry',`${x*5}deg`);art.style.setProperty('--cursor-x',`${(x+.5)*100}%`);art.style.setProperty('--cursor-y',`${(y+.5)*100}%`);dots.forEach((dot,i)=>{const dx=((i*29)%100)/100-.5,dy=((i*47)%100)/100-.5,dist=Math.hypot(x-dx,y-dy),push=Math.max(0,1-dist*2.8);dot.style.transform=`translate(${(x-dx)*-18*push}px,${(y-dy)*-18*push}px) scale(${1+push*.35})`;dot.style.boxShadow=push?`0 0 ${14+push*18}px rgba(32,243,251,.75)`:''})});art.addEventListener('pointerleave',()=>{art.classList.remove('is-hovering');art.style.setProperty('--mx','0px');art.style.setProperty('--my','0px');art.style.setProperty('--rx','0deg');art.style.setProperty('--ry','0deg');dots.forEach(d=>{d.style.transform='';d.style.boxShadow=''})});art.addEventListener('pointerdown',()=>{art.classList.remove('hit');void art.offsetWidth;art.classList.add('hit')})}
/* 3D card hover */
if(!reduce&&!coarse){document.querySelectorAll('.service,.page-card,.ai-grid article,.why-grid article,.steps article,.arch-card,.engagement,.digital-card,.protocol,.live-console').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--card-rx',`${-y*5}deg`);card.style.setProperty('--card-ry',`${x*6}deg`);card.style.setProperty('--spot-x',`${(x+.5)*100}%`);card.style.setProperty('--spot-y',`${(y+.5)*100}%`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--card-rx','0deg');card.style.setProperty('--card-ry','0deg')})});document.querySelectorAll('.btn').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`translate(${x*3}px,${y*3}px) translateY(-2px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
/* Active navigation */
const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===page||(page===''&&a.getAttribute('href')==='index.html'))a.setAttribute('aria-current','page')});})();