const ALLOWED_ORIGIN='https://deepdell.com';
const ENDPOINTS=[
{group:'Core',name:'robots.txt',path:'/robots.txt',standard:true},{group:'Core',name:'sitemap.xml',path:'/sitemap.xml',standard:true},{group:'Core',name:'sitemap index',path:'/sitemap_index.xml',standard:true},
{group:'AI Discovery',name:'llms.txt',path:'/llms.txt',standard:true},{group:'AI Discovery',name:'llms-full.txt',path:'/llms-full.txt'},{group:'AI Discovery',name:'llms.md',path:'/llms.md'},{group:'AI Discovery',name:'llms-full.md',path:'/llms-full.md'},
{group:'Agent Docs',name:'agent.md',path:'/agent.md'},{group:'Agent Docs',name:'agents.md',path:'/agents.md'},{group:'Agent Docs',name:'agent.json',path:'/agent.json'},{group:'Agent Docs',name:'agents.json',path:'/agents.json'},{group:'Agent Docs',name:'ai.txt',path:'/ai.txt'},{group:'Agent Docs',name:'ai.md',path:'/ai.md'},{group:'Agent Docs',name:'ai.json',path:'/ai.json'},{group:'Agent Docs',name:'model-context.md',path:'/model-context.md'},
{group:'Well-known',name:'UCP profile',path:'/.well-known/ucp',standard:true},{group:'Well-known',name:'A2A Agent Card',path:'/.well-known/agent-card.json',standard:true},{group:'Well-known',name:'AI plugin',path:'/.well-known/ai-plugin.json'},{group:'Well-known',name:'OpenID configuration',path:'/.well-known/openid-configuration'},{group:'Well-known',name:'OAuth authorization server',path:'/.well-known/oauth-authorization-server'},
{group:'Protocol',name:'UCP MCP endpoint',path:'/ucp/mcp'},{group:'Protocol',name:'MCP endpoint',path:'/mcp'},{group:'Protocol',name:'MCP SSE endpoint',path:'/sse'},{group:'Protocol',name:'API MCP endpoint',path:'/api/mcp'},
{group:'Additional',name:'security.txt',path:'/security.txt'},{group:'Additional',name:'humans.txt',path:'/humans.txt'},{group:'Additional',name:'sitemap.txt',path:'/sitemap.txt'},{group:'Additional',name:'agentic.md',path:'/agentic.md'},{group:'Additional',name:'agentic.json',path:'/agentic.json'}];
const json=(body,status=200,origin=ALLOWED_ORIGIN)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});
function normalize(value){let u;try{u=new URL(String(value||'').trim())}catch{throw new Error('Please enter a valid website URL.')}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw new Error('Only public HTTP/HTTPS URLs are supported.');const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.localhost')||h==='0.0.0.0'||h==='::1'||/^(10|127|169\\.254)\\./.test(h)||/^192\\.168\\./.test(h)||/^172\\.(1[6-9]|2\\d|3[0-1])\\./.test(h))throw new Error('Private network URLs are not allowed.');u.hash='';u.search='';return u}
async function get(url,timeout){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout||7000);try{return await fetch(url,{redirect:'follow',headers:{'User-Agent':'DEEPDELL-Agentic-Readiness/1.0 (+https://deepdell.com/agentic-check.html)',Accept:'text/html,application/json,text/plain,*/*'},signal:c.signal})}finally{clearTimeout(t)}}
const found=s=>s>=200&&s<400||[401,403,405,406,415,422].includes(s);
const capture=(html,re)=>{const m=html.match(re);return m?m[1].replace(/\\s+/g,' ').trim():''};
function homeScore(html,status,base){const title=capture(html,/<title[^>]*>([\\s\\S]*?)<\\/title>/i);const desc=capture(html,/<meta[^>]+name=['"]description['"][^>]+content=['"]([^'"]*)['"][^>]*>/i)||capture(html,/<meta[^>]+content=['"]([^'"]*)['"][^>]+name=['"]description['"][^>]*>/i);const canon=capture(html,/<link[^>]+rel=['"]canonical['"][^>]+href=['"]([^'"]+)['"][^>]*>/i)||capture(html,/<link[^>]+href=['"]([^'"]+)['"][^>]+rel=['"]canonical['"][^>]*>/i);let canonicalOk=false;try{canonicalOk=canon?new URL(canon,base).origin===new URL(base).origin:false}catch{}const h1=/<h1\\b/i.test(html),lang=/<html[^>]+lang=['"][^'"]+['"]/i.test(html),og=/<meta[^>]+property=['"]og:(title|description|url)['"]/i.test(html),jsonLd=/<script[^>]+type=['"]application\\/ld\\+json['"]/i.test(html),text=html.replace(/<script[\\s\\S]*?<\\/script>|<style[\\s\\S]*?<\\/style>|<[^>]+>/gi,' ').replace(/\\s+/g,' ').trim();const technical=Math.min(20,(status>=200&&status<400?2:0)+(title.length>=20&&title.length<=65?3:0)+(desc.length>=70&&desc.length<=170?3:0)+(canonicalOk?3:0)+(h1?2:0)+(lang?2:0)+(og?2:0)+(jsonLd?3:0));return{status,title,description:desc,canonical,checks:{h1,lang,og,jsonLd,canonicalOk,headings:(html.match(/<h[2-6]\\b/gi)||[]).length,readableText:text.length>=500},technicalSeo:technical}}
async function audit(baseUrl){const base=baseUrl.origin+'/';let home;try{home=await get(baseUrl.href,10000)}catch(e){throw new Error('Could not reach the public homepage: '+(e.name==='AbortError'?'request timed out':'network request failed')+'.')}const homepage=homeScore(await home.text(),home.status,base);const results=await Promise.all(ENDPOINTS.map(async item=>{try{const r=await get(new URL(item.path,base).href,6000);let validJson=null;if(item.path.endsWith('.json')||item.path==='/.well-known/ucp'){if((r.headers.get('content-type')||'').includes('json')){try{await r.clone().json();validJson=true}catch{validJson=false}}}return Object.assign({},item,{status:r.status,found:found(r.status),validJson})}catch{return Object.assign({},item,{status:0,found:false,validJson:null})}}));const has=n=>results.some(x=>x.name===n&&x.found),docs=results.filter(x=>x.group==='Agent Docs'&&x.found).length,additional=results.filter(x=>x.group==='Additional'&&x.found).length;const categories={technicalSeo:homepage.technicalSeo,machineDiscovery:Math.min(20,(has('robots.txt')?5:0)+(has('sitemap.xml')?5:0)+(has('sitemap index')?2:0)+(has('security.txt')?1:0)+(has('sitemap.txt')?1:0)+Math.min(3,additional)+(has('llms.txt')?3:0)),llmReadability:Math.min(20,(has('llms.txt')?8:0)+(has('llms-full.txt')?4:0)+(has('llms.md')?2:0)+(has('llms-full.md')?2:0)+(docs?4:0)),agentIdentity:Math.min(20,(has('UCP profile')?8:0)+(has('A2A Agent Card')?8:0)+(docs?4:0)),agentProtocols:Math.min(20,(has('UCP MCP endpoint')?5:0)+(has('MCP endpoint')?5:0)+(has('MCP SSE endpoint')?3:0)+(has('API MCP endpoint')?3:0)+(results.some(x=>x.group==='Protocol'&&x.found)?4:0))};return{ok:true,base,homepage,categories,total:Object.values(categories).reduce((a,b)=>a+b,0),results}}
async function handle(request){const origin=request.headers.get('Origin');if(origin&&origin!==ALLOWED_ORIGIN)return json({error:'Origin not allowed.'},403);let value='';if(request.method==='GET')value=new URL(request.url).searchParams.get('url')||'';else{try{value=(await request.json()).url||''}catch{return json({error:'Invalid request body.'},400)}}try{return json(await audit(normalize(value)))}catch(e){return json({error:e.message||'Audit failed.'},400)}}
export function onRequestOptions({request}){const origin=request.headers.get('Origin')||ALLOWED_ORIGIN;return json({ok:true},200,origin===ALLOWED_ORIGIN?origin:ALLOWED_ORIGIN)}
export function onRequestGet({request}){return handle(request)}
export function onRequestPost({request}){return handle(request)}
